#! /bin/sh

sxhkd &

bspc monitor -d 1 2 3 4 5 6 7

bspc config border_width         1
bspc config window_gap          20
bspc config top_padding		18

#bspc config pointer_modifier mod4
#bspc config pointer_action1 move
#bspc config pointer_action2 resize_side
#bspc config pointer_action1 resize_corner

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc config active_border_color     '#AAAAAA' #'#b02f30'
bspc config focused_border_color    '#AAAAAA' #'#b02f30'
bspc config normal_border_color     '#000000' #'#237986'

bspc rule -a Gimp desktop='^7' state=floating follow=on
bspc rule -a Vivaldi-stable desktop='^2'
bspc rule -a Thunderbird desktop='^3'
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

$HOME/.config/polybar/launch.sh

xset -dpms s off
nm-applet &
feh --bg-scale $HOME/Pictures/archlabs.png
compton --config $HOME/.config/compton.conf -b
dunst -config .config/dunst/dunstrc
